-- MySQL Script generated by MySQL Workbench
-- sáb 08 oct 2016 18:03:31 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema QRemis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QRemis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QRemis` DEFAULT CHARACTER SET utf8 ;
USE `QRemis` ;

-- -----------------------------------------------------
-- Table `QRemis`.`Parada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`Parada` (
  `idParada` INT NOT NULL AUTO_INCREMENT,
  `Parada` VARCHAR(45) NULL,
  `lat` DOUBLE NULL,
  `lon` DOUBLE NULL,
  PRIMARY KEY (`idParada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`Movil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`Movil` (
  `idMovil` INT NOT NULL AUTO_INCREMENT,
  `idParada` INT NULL,
  `modelo` VARCHAR(45) NULL,
  `estado` INT NULL,
  `added` DATETIME NULL,
  `lat` DOUBLE NULL,
  `lon` DOUBLE NULL,
  PRIMARY KEY (`idMovil`),
  INDEX `fk_Movil_Parada1_idx` (`idParada` ASC),
  CONSTRAINT `fk_Movil_Parada1`
    FOREIGN KEY (`idParada`)
    REFERENCES `QRemis`.`Parada` (`idParada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `telefono` DOUBLE NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `lat` DOUBLE NULL,
  `lon` DOUBLE NULL,
  PRIMARY KEY (`idCliente`, `telefono`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`sec_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`sec_Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `Rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`sec_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`sec_Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idRol` INT NOT NULL,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido` VARCHAR(45) NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`, `idRol`),
  INDEX `fk_Usuario_Rol1_idx` (`idRol` ASC),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `QRemis`.`sec_Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`Llamadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`Llamadas` (
  `idLlamadas` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `fecha` DATETIME NULL,
  `telefono` DOUBLE NULL,
  `duracion` TIME NULL,
  `estado` INT NULL,
  `grabacion` VARCHAR(100) NULL,
  PRIMARY KEY (`idLlamadas`),
  INDEX `fk_Llamadas_sec_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Llamadas_sec_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `QRemis`.`sec_Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`Alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`Alquiler` (
  `idAlquiler` INT NOT NULL AUTO_INCREMENT,
  `idMovil` INT NULL,
  `idParada` INT NULL,
  `idCliente` INT NOT NULL,
  `idLlamadas` INT NOT NULL,
  `telefono` DOUBLE NOT NULL,
  `fecha` DATETIME NULL,
  `origen` VARCHAR(45) NULL,
  `origen_lat` DOUBLE NULL,
  `origen_lon` DOUBLE NULL,
  `destino` VARCHAR(45) NULL,
  `destino_lat` DOUBLE NULL,
  `destino_lon` DOUBLE NULL,
  `km` INT NULL,
  `fechaAtencion` DATETIME NULL,
  PRIMARY KEY (`idAlquiler`),
  INDEX `fk_Alquiler_Moviles_idx` (`idMovil` ASC),
  INDEX `fk_Alquiler_Llamadas1_idx` (`idLlamadas` ASC),
  INDEX `fk_Alquiler_Cliente1_idx` (`idCliente` ASC, `telefono` ASC),
  INDEX `fk_Alquiler_Parada1_idx` (`idParada` ASC),
  CONSTRAINT `fk_Alquiler_Moviles`
    FOREIGN KEY (`idMovil`)
    REFERENCES `QRemis`.`Movil` (`idMovil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Llamadas1`
    FOREIGN KEY (`idLlamadas`)
    REFERENCES `QRemis`.`Llamadas` (`idLlamadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Cliente1`
    FOREIGN KEY (`idCliente` , `telefono`)
    REFERENCES `QRemis`.`Cliente` (`idCliente` , `telefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Parada1`
    FOREIGN KEY (`idParada`)
    REFERENCES `QRemis`.`Parada` (`idParada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`sec_Plugin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`sec_Plugin` (
  `idPlugin` INT NOT NULL AUTO_INCREMENT,
  `Plugin` VARCHAR(45) NULL DEFAULT NULL,
  `autor` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `key` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPlugin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`sec_RolDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`sec_RolDetalle` (
  `idRolDetalle` INT NOT NULL AUTO_INCREMENT,
  `idRol` INT NOT NULL,
  `idPlugin` INT NOT NULL,
  PRIMARY KEY (`idRolDetalle`, `idRol`),
  INDEX `fk_table1_Rol1_idx` (`idRol` ASC),
  INDEX `fk_sec_RolDetalle_sec_Plugin1_idx` (`idPlugin` ASC),
  CONSTRAINT `fk_table1_Rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `QRemis`.`sec_Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sec_RolDetalle_sec_Plugin1`
    FOREIGN KEY (`idPlugin`)
    REFERENCES `QRemis`.`sec_Plugin` (`idPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`Multas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`Multas` (
  `idMulta` INT NOT NULL AUTO_INCREMENT,
  `idMovil` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `inicio` DATETIME NULL,
  `fin` DATETIME NULL,
  PRIMARY KEY (`idMulta`),
  INDEX `fk_Multas_Movil1_idx` (`idMovil` ASC),
  INDEX `fk_Multas_sec_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Multas_Movil1`
    FOREIGN KEY (`idMovil`)
    REFERENCES `QRemis`.`Movil` (`idMovil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Multas_sec_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `QRemis`.`sec_Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QRemis`.`sec_Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`sec_Log` (
  `idSec_Log` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idRol` INT NOT NULL,
  `fecha` DATETIME NULL,
  `msg` VARCHAR(45) NULL,
  PRIMARY KEY (`idSec_Log`),
  INDEX `fk_sec_Log_sec_Usuario1_idx` (`idUsuario` ASC, `idRol` ASC),
  CONSTRAINT `fk_sec_Log_sec_Usuario1`
    FOREIGN KEY (`idUsuario` , `idRol`)
    REFERENCES `QRemis`.`sec_Usuario` (`idUsuario` , `idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `QRemis` ;

-- -----------------------------------------------------
-- Placeholder table for view `QRemis`.`VMoviles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`VMoviles` (`idMovil` INT, `idParada` INT, `modelo` INT, `estado` INT, `added` INT, `lat` INT, `lon` INT);

-- -----------------------------------------------------
-- Placeholder table for view `QRemis`.`VEspera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`VEspera` (`idAlquiler` INT, `idMovil` INT, `idParada` INT, `idCliente` INT, `idLlamadas` INT, `telefono` INT, `fecha` INT, `origen` INT, `origen_lat` INT, `origen_lon` INT, `destino` INT, `destino_lat` INT, `destino_lon` INT, `km` INT, `fechaAtencion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `QRemis`.`VAtendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`VAtendidos` (`idAlquiler` INT, `idMovil` INT, `idParada` INT, `idCliente` INT, `idLlamadas` INT, `telefono` INT, `fecha` INT, `origen` INT, `origen_lat` INT, `origen_lon` INT, `destino` INT, `destino_lat` INT, `destino_lon` INT, `km` INT, `fechaAtencion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `QRemis`.`VParadaDist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QRemis`.`VParadaDist` (`idParada` INT, `Parada` INT, `lat` INT, `lon` INT, `idCliente` INT, `dist` INT);

-- -----------------------------------------------------
-- function fdistance
-- -----------------------------------------------------

DELIMITER $$
USE `QRemis`$$
CREATE FUNCTION fdistance(lat1 double, lon1 double, lat2 double, lon2 double) RETURNS double
BEGIN
	return ( 3959 * acos( cos( radians(lat1) ) * 
			   cos( radians(lat2) ) * 
               cos( radians(lon2) - radians(lon1) ) + 
               sin( radians(lat1) ) * sin( radians( lat2 ) ) ) );
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `QRemis`.`VMoviles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QRemis`.`VMoviles`;
USE `QRemis`;
CREATE  OR REPLACE VIEW `VMoviles` AS
SELECT * FROM Movil WHERE estado != 3;

-- -----------------------------------------------------
-- View `QRemis`.`VEspera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QRemis`.`VEspera`;
USE `QRemis`;
CREATE  OR REPLACE VIEW `VEspera` AS
SELECT * FROM Alquiler WHERE isNull(fechaAtencion);

-- -----------------------------------------------------
-- View `QRemis`.`VAtendidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QRemis`.`VAtendidos`;
USE `QRemis`;
CREATE  OR REPLACE VIEW `VAtendidos` AS
SELECT * FROM Alquiler WHERE NOT isNull(fechaAtencion) 
ORDER BY fechaAtencion desc;

-- -----------------------------------------------------
-- View `QRemis`.`VParadaDist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QRemis`.`VParadaDist`;
USE `QRemis`;
CREATE  OR REPLACE VIEW `VParadaDist` AS
SELECT p.*, c.idCliente, fdistance(c.lat, c.lon, p.lat, p.lon) as dist
FROM Parada as p JOIN Cliente as c
ORDER BY dist asc LIMIT 1;

-- -----------------------------------------------------
-- ADD VALUES
-- -----------------------------------------------------
INSERT INTO sec_Rol (idRol, Rol) VALUES (1, 'Administrador'), (2, 'Operador');
INSERT INTO sec_Usuario (idRol, user, pass, Nombre) VALUE (1, 'admin', md5('admin'), 'Administrador');

INSERT INTO Parada (Parada) VALUES ('Parada 1'), ('Parada 2');
INSERT INTO Movil (modelo) VALUES ('Desconociodo'), ('Desconociodo'), ('Desconociodo'), ('Desconociodo');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
