Document: qmlremis
Title: Debian qmlremis Manual
Author: <insert document author here>
Abstract: This manual describes what qmlremis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qmlremis/qmlremis.sgml.gz

Format: postscript
Files: /usr/share/doc/qmlremis/qmlremis.ps.gz

Format: text
Files: /usr/share/doc/qmlremis/qmlremis.text.gz

Format: HTML
Index: /usr/share/doc/qmlremis/html/index.html
Files: /usr/share/doc/qmlremis/html/*.html
